/*
 *
 * Copyright (C) 2016 Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

#ifndef UVD_3_1_SH_MASK_H
#define UVD_3_1_SH_MASK_H

#define UVD_CGC_CTRL2__DYN_OCLK_RAMP_EN_MASK 0x00000001L
#define UVD_CGC_CTRL2__DYN_OCLK_RAMP_EN__SHIFT 0x00000000
#define UVD_CGC_CTRL2__DYN_RCLK_RAMP_EN_MASK 0x00000002L
#define UVD_CGC_CTRL2__DYN_RCLK_RAMP_EN__SHIFT 0x00000001
#define UVD_CGC_CTRL2__GATER_DIV_ID_MASK 0x0000001cL
#define UVD_CGC_CTRL2__GATER_DIV_ID__SHIFT 0x00000002
#define UVD_CGC_CTRL__CLK_GATE_DLY_TIMER_MASK 0x0000003cL
#define UVD_CGC_CTRL__CLK_GATE_DLY_TIMER__SHIFT 0x00000002
#define UVD_CGC_CTRL__CLK_OFF_DELAY_MASK 0x000007c0L
#define UVD_CGC_CTRL__CLK_OFF_DELAY__SHIFT 0x00000006
#define UVD_CGC_CTRL__DYN_CLOCK_MODE_MASK 0x00000001L
#define UVD_CGC_CTRL__DYN_CLOCK_MODE__SHIFT 0x00000000

#define UVD_CGC_GATE__REGS_MASK 0x00000008L
#define UVD_CGC_GATE__REGS__SHIFT 0x00000003

#define UVD_SOFT_RESET__CSM_SOFT_RESET_MASK 0x00000020L
#define UVD_SOFT_RESET__CSM_SOFT_RESET__SHIFT 0x00000005
#define UVD_SOFT_RESET__CXW_SOFT_RESET_MASK 0x00000040L
#define UVD_SOFT_RESET__CXW_SOFT_RESET__SHIFT 0x00000006

#define UVD_SOFT_RESET__LBSI_SOFT_RESET_MASK 0x00000002L
#define UVD_SOFT_RESET__LBSI_SOFT_RESET__SHIFT 0x00000001

#define UVD_SOFT_RESET__LMI_SOFT_RESET_MASK 0x00000004L
#define UVD_SOFT_RESET__LMI_SOFT_RESET__SHIFT 0x00000002
#define UVD_SOFT_RESET__LMI_UMC_SOFT_RESET_MASK 0x00002000L
#define UVD_SOFT_RESET__LMI_UMC_SOFT_RESET__SHIFT 0x0000000d

#define UVD_SOFT_RESET__RBC_SOFT_RESET_MASK 0x00000001L
#define UVD_SOFT_RESET__RBC_SOFT_RESET__SHIFT 0x00000000

#define UVD_SOFT_RESET__TAP_SOFT_RESET_MASK 0x00000080L
#define UVD_SOFT_RESET__TAP_SOFT_RESET__SHIFT 0x00000007

#define UVD_SOFT_RESET__VCPU_SOFT_RESET_MASK 0x00000008L
#define UVD_SOFT_RESET__VCPU_SOFT_RESET__SHIFT 0x00000003


#endif
